driver: add a way to load logo from config partition
radxa/u-boot pull request #101
Opened 2024-10-12 10:38 UTC by nascs

2024-10-12 10:40 UTC, nascs commented
bmp 图片像素 width * height  不超过 200000

2024-10-14 03:22 UTC, RadxaYuntian requested changes

2024-10-14 03:22 UTC, RadxaYuntian commented on arch/arm/include/asm/arch-rockchip/radxa_img.h
> +
```suggestion
```

2024-10-14 03:22 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/radxa_img.c
> +
```suggestion
```

2024-10-14 03:22 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/radxa_img.c
> +    return len;
```suggestion
	return len;
```

2024-10-14 03:22 UTC, RadxaYuntian commented on drivers/video/drm/rockchip_display.c
> +// #ifdef CONFIG_ROCKCHIP_RESOURCE_IMAGE
```suggestion
#ifdef CONFIG_ROCKCHIP_RESOURCE_IMAGE
```
不要破坏原本的代码逻辑

2024-10-14 03:22 UTC, RadxaYuntian commented on drivers/video/drm/rockchip_display.c
> -#endif
恢复之前的代码流程

2024-10-14 03:22 UTC, RadxaYuntian commented on drivers/video/drm/rockchip_display.c
> +#endif
```suggestion
#ifdef CONFIG_RADXA_IMG
	len = radxa_read_bmp_file(bmp_data, bmp_name);
#else
	len = rockchip_read_resource_file(bmp_data, bmp_name, 0, MAX_IMAGE_BYTES);
#endif
```
更好的是在radxa_read_bmp_file调用后如果失败的话，再调用rockchip_read_resource_file

2024-10-14 03:22 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/radxa_img.c
> +int radxa_read_bmp_file(void *buf, const char *name) {
除了config分区还有我们root分区的plymouth配置，要看看那个的logo路径，作为config找不到的fallback

2024-10-14 07:08 UTC, nascs commented on arch/arm/mach-rockchip/radxa_img.c
> +int radxa_read_bmp_file(void *buf, const char *name) {
还需要从 root 分区读取？

2024-10-14 07:12 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/radxa_img.c
> +int radxa_read_bmp_file(void *buf, const char *name) {
正常开机logo应该是这个：https://github.com/radxa-pkg/radxa-plymouth-theme/blob/main/theme/logo.png
config分区是给用户一个用他们自己logo的选项。
不过现在这个png可能识别不了，先不弄吧，下一步再看是不是要修改格式

2024-10-14 08:29 UTC, nascs commented on drivers/video/drm/rockchip_display.c
> -#endif
最新的 commit 已经恢复了

2024-10-14 10:23 UTC, RadxaYuntian commented on drivers/video/drm/rockchip_display.c
> -#endif
改好了点request for review

2024-10-14 10:48 UTC, nascs commented
看一下这个 pr 还有什么问题？

2024-10-15 02:57 UTC, RadxaYuntian requested changes

2024-10-15 02:57 UTC, RadxaYuntian commented on drivers/video/drm/rockchip_display.c
> +	len = radxa_read_bmp_file(bmp_data, bmp_name);
1. 测试过找不到图片的现象么？
2. 加上radxa_read_bmp_file如果调用失败后改用rockchip_read_resource_file的fallback

2024-10-15 06:28 UTC, nascs commented on drivers/video/drm/rockchip_display.c
> +	len = radxa_read_bmp_file(bmp_data, bmp_name);
加了 CONFIG_RADXA_IMG 这个宏，如果 config 分区没有找到 logo.bmp logo_kernel.bmp：
===== radxa read bmp file =====
File logo.bmp does not exist
failed to display uboot logo


没加 CONFIG_RADXA_IMG 这个宏，走 rockchip_read_resource_file：
===== rockchip read resource file =====
No resource file: logo.bmp

2024-10-17 11:01 UTC, RadxaYuntian requested changes
用#ifdef把相关的代码排除到编译路径之外

2024-10-18 01:59 UTC, RadxaYuntian requested changes

2024-10-18 01:59 UTC, RadxaYuntian commented on drivers/video/drm/rockchip_display.c
> +
```suggestion
	if(len < 0) {
#endif
		len = rockchip_read_resource_file(bmp_data, bmp_name, 0, MAX_IMAGE_BYTES);
#ifdef CONFIG_RADXA_IMG
	}
#endif
```
减少重复的代码

2024-10-18 07:10 UTC, RadxaYuntian requested changes
squash一下

2024-10-18 09:18 UTC, RadxaYuntian requested changes

2024-10-18 09:18 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/Kconfig
> +	default n
```suggestion
	depends on ROCKCHIP_RESOURCE_IMAGE
	default y
```

2024-10-20 14:50 UTC, ehsan6sha approved these changes

2024-10-21 06:29 UTC, RadxaYuntian approved these changes

2024-10-22 04:01 UTC, merged