Port rock3b to rknext radxa display dtsi
radxa/u-boot pull request #102
Opened 2024-10-22 09:03 UTC by nascs

2024-10-22 09:51 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-display.dtsi
你这是我们LCD屏幕dtsi么？为什么屏幕还包含了其他不相关的部件？

2024-10-22 09:58 UTC, nascs commented on arch/arm/dts/rk3568-radxa-display.dtsi
这个是 rk3568.dtsi 缺少的部分，为了不影响以后 rk 的修改，所以单独新建一个 dtsi， 主要是为了补全 display_subsystem 节点中的 devfreq 属性

2024-10-22 10:05 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-display.dtsi
问题是为什么要添加？buildroot的dts不也可以显示logo么？

2024-10-22 10:16 UTC, nascs commented on arch/arm/dts/rk3568-radxa-display.dtsi
buildroot 里面， u-boot 和 kernel 用同一份 dts

2024-10-22 10:17 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-display.dtsi
那把uboot的rk3568.dtsi和内核的同步一下吧。这个单独一个commit，以后同步方便drop掉

2024-10-23 10:30 UTC, nascs commented on arch/arm/dts/rk3568-radxa-display.dtsi
我感觉这样写也可以, 就是要把 rk3568-radxa-display.dtsi 单独写成一个 commit

刚刚看了一下 rk3588 的 u-boot, 里面连 display_subsystem 这个节点都没有, 感觉 rk 并不打算在 u-boot 里面配这个节点的样子

另外 u-boot 和 kernel 的 rk3568.dtsi 差异很大

2024-10-24 02:38 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-display.dtsi
差异大你不也说了buildroot两个的dts是一样的么

2024-10-24 02:44 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-display.dtsi
你是不是直接把内核的设备树复制过来就好了

2024-10-24 02:57 UTC, nascs commented on arch/arm/dts/rk3568-radxa-display.dtsi
> 差异大你不也说了buildroot两个的dts是一样的么

buildroot 是直接用 kernel 里面的 dts, 只是驱动是 u-boot 里面的驱动.
在 buildroot 里面添加我们的一个产品,应该只需要把 dts 丢到 kernel/arch/arm64/boot/dts/rockchip 里面,然后在添加一份相关配置就好, u-boot 那边不需要做任何操作

2024-10-24 03:23 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-display.dtsi
这才是正确的方式。uboot和内核的dts就应该是同步的。

2024-10-30 11:07 UTC, nascs commented
usb 暂时不能用, rk356x 的 usb 是一个共性问题, 我先关闭吧, 后面再一起看看

2024-10-30 11:16 UTC, nascs commented on arch/arm/dts/rk3568-rock-3b.dts
> +	pcie30_3v3: gpio-regulator {
这个电, 从 kernel 那边拷贝过来的有问题, 但是把这个给 kernel 是没问题的

2024-10-31 03:12 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-rock-3b.dts
> +	pcie30_3v3: gpio-regulator {
这个电有什么问题？

2024-10-31 05:57 UTC, nascs commented on arch/arm/dts/rk3568-rock-3b.dts
> +	pcie30_3v3: gpio-regulator {
就是原本 kernel 是给 pcie3x1 和 pcie3x2 配的,但是实际上 u-boot 这里对 pcie2x1 也有影响.

2024-10-31 07:50 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-rock-3b.dts
> +	pcie30_3v3: gpio-regulator {
我在邮件里面看到有定义`u-boot,dm-pre-reloc;`，这种属性应该都挪到`rk3568-rock-3b-u-boot.dtsi`，并且仅在uboot需要的时候才开启。

2024-11-01 09:14 UTC, nascs commented
@RadxaYuntian 帮忙看看哪里还有问题?

2024-11-04 03:23 UTC, RadxaYuntian requested changes

2024-11-04 03:23 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-u-boot.dtsi
> +	compatible = "rockchip,dwcmshc-sdhci", "snps,dwcmshc-sdhci";
这些改动应该是因为uboot的驱动和linux的不太一样对吧？

2024-11-04 03:23 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-rock-3b-u-boot.dtsi
我感觉接口相关几乎都可以放到rk3568-u-boot里面，电才可能需要放到产品自己的u-boot.dtsi里面

2024-11-04 03:23 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-rock-3b.dts
>  		compatible = "pwm-fan";
所以你这个文件到底是不是内核过来的？还是说内核里的也有这些uboot的tag？

2024-11-04 11:47 UTC, nascs commented on arch/arm/dts/rk3568-u-boot.dtsi
> +	compatible = "rockchip,dwcmshc-sdhci", "snps,dwcmshc-sdhci";
是的

2024-11-04 12:08 UTC, nascs commented on arch/arm/dts/rk3568-rock-3b.dts
>  		compatible = "pwm-fan";
> 所以你这个文件到底是不是内核过来的？还是说内核里的也有这些uboot的tag？

[fa106f5](https://github.com/radxa/u-boot/pull/102/commits/fa106f5476e92c3a463775e0d1d4e6bcb7dff664) 这个是从 kernel 拷过来的, 后面改了pcie30_3v3, 再加了display_subsystem 和 vp0_out_hdmi

2024-11-04 12:18 UTC, nascs commented on arch/arm/dts/rk3568-rock-3b.dts
>  		compatible = "pwm-fan";
> > 所以你这个文件到底是不是内核过来的？还是说内核里的也有这些uboot的tag？
> 
> [fa106f5](https://github.com/radxa/u-boot/pull/102/commits/fa106f5476e92c3a463775e0d1d4e6bcb7dff664) 这个是从 kernel 拷过来的, 后面改了pcie30_3v3, 再加了display_subsystem 和 vp0_out_hdmi

这些改动是否需要加到 kernel 的 dts 里面? pcie30_3v3 验证过, 在 kernel 那边的 dts 也是可以用的

2024-11-05 03:36 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-rock-3b.dts
>  		compatible = "pwm-fan";
你改动太多了，我都不确定你说的是什么改动。不过内核的设备树不应该有u-boot的tag

2024-11-05 07:56 UTC, nascs commented on arch/arm/dts/rk3568-rock-3b.dts
> +	pcie30_3v3: gpio-regulator {
> 就是原本 kernel 是给 pcie3x1 和 pcie3x2 配的,但是实际上 u-boot 这里对 pcie2x1 也有影响.

这里搞错了, 对 pcie2x1 没影响, 我把 pcie2x1 看成 M-Key 了, pcie3x2 才是 M-Key

2024-11-05 10:47 UTC, RadxaYuntian reviewed
在内核那边把电改对，然后这边同步吧。别的没啥问题了

2024-11-21 12:17 UTC, nascs commented
这边看看还有什么问题？ 论坛有个用户用 latest 的 u-boot 卡在 pcie 那边了， 这里没问题的话， 我后面让用户用这个分支？

2024-11-22 03:26 UTC, RadxaYuntian commented
@RadxaStephen 是不是rebase到2024.10算了

2024-11-22 03:33 UTC, RadxaStephen commented
重新整理一下提交吧。把一些 commit 合并到一起。

2024-11-22 03:34 UTC, RadxaStephen commented
> @RadxaStephen 是不是rebase到2024.10算了

也是，切到 v2024.10。

2024-11-22 09:54 UTC, nascs commented
看看还有什么问题？

2024-11-22 09:59 UTC, RadxaYuntian commented
你本地先rebase到2024.10分支上

2024-11-22 12:35 UTC, RadxaStephen reviewed
需要参考的 kernel 原始文件来自于哪里

2025-01-27 07:33 UTC, nascs commented
这个 pr 又得重整了， 是按 cm5-io 那样整对吧

2025-01-27 07:34 UTC, RadxaYuntian commented
为什么又要重新弄？你这个功能难道还有什么问题么

2025-01-27 07:38 UTC, closed without merging