usb boot support
radxa/u-boot pull request #24
Opened 2023-05-19 08:35 UTC by vamrs-feng

2023-05-19 09:12 UTC, RadxaYuntian requested changes

2023-05-19 09:12 UTC, RadxaYuntian commented on arch/arm/dts/rk3588-rock-5b.dts
`u-boot,dm-pre-reloc;`一般是放到`rk3588-rock-5b-u-boot.dtsi`文件里面的，而`rk3588-rock-5b.dts`这个文件则是和Linux里面的同名dts保持同步

2023-05-22 07:57 UTC, RadxaYuntian reviewed
还是不规范。stephen没意见的话就这样吧

2023-05-29 02:25 UTC, RadxaStephen commented
mainline u-boot dts 都有 soc-board-u-boot.dts，像 rk3588-rock-5b-u-boot.dtsi

我看到 rockchip u-boot rk3588 evb 也没写。

2023-06-02 06:38 UTC, merged