add radxa cm3i-io support
radxa/u-boot pull request #57
Opened 2024-01-19 02:14 UTC by Radxa-Alvin

2024-01-19 03:22 UTC, RadxaYuntian reviewed
cm3i和e61我们到底叫哪个名字

2024-01-19 06:07 UTC, Radxa-Alvin commented
e61改名为 cm3i-io，之前相关的仓库已经全改过了

2024-01-23 02:42 UTC, RadxaYuntian requested changes

2024-01-23 02:42 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-e25.dts
> +};
缺少结尾空行

2024-01-24 03:23 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-cm3i-io.dts
> +	model = "Radxa CM3I IO Board";
我们现在有发布cm3i io的系统么？Linux那边也更正了么？

2024-01-24 03:23 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-cm3i-io.dts
> +	model = "Radxa CM3I IO Board";
另外你这个commit回头直接和第一个commit合并一下

2024-01-24 03:31 UTC, Radxa-Alvin commented on arch/arm/dts/rk3568-radxa-cm3i-io.dts
> +	model = "Radxa CM3I IO Board";
CM3I-IO 内核已经改过来了 编过一个test 版本了，我修改强推一下

2024-01-28 08:00 UTC, RadxaStephen commented
Applied to next-dev branch.

2024-01-28 08:00 UTC, closed without merging