drivers: misc: add radxa eeprom support
radxa/u-boot pull request #71
Opened 2024-05-21 10:10 UTC by Radxa-Alvin

Read eeprom data in Radxa specified format
and set mac address read from eeprom.

2024-05-21 11:32 UTC, RadxaYuntian requested changes

2024-05-21 11:32 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/misc.c
> +	if(!mac_read_from_eeprom())
失败了继续后面的代码，完成默认的以太网配置

2024-05-21 11:32 UTC, RadxaYuntian commented on drivers/misc/Kconfig
> +         This driver aims to dump specified values of eeprom.
描述说具体点

2024-05-21 11:32 UTC, RadxaYuntian commented on drivers/misc/Makefile
> +obj-$(CONFIG_RADXA_ID_EEPROM) += radxa-i2c-eeprom.ogit
```suggestion
obj-$(CONFIG_RADXA_ID_EEPROM) += radxa-i2c-eeprom.o
```

2024-05-21 11:32 UTC, RadxaYuntian commented on drivers/misc/Kconfig
> +       bool "Radxa eeprom Support"
```suggestion
       bool "Enable Radxa ID EEPROM driver"
```
另外这个Radxa ID EEPROM名字感觉很怪，platform data之类的可能更适当一些

2024-05-21 11:32 UTC, RadxaYuntian commented on drivers/misc/radxa-i2c-eeprom.c
代码最好是引用board/starfive/visionfive2/visionfive2-i2c-eeprom.c，然后在那个文件里面修改，这样我们后面才方便提交到上游

2024-05-22 02:03 UTC, Radxa-Alvin commented on arch/arm/mach-rockchip/misc.c
> +	if(!mac_read_from_eeprom())
这里是成功了return，失败了接着跑

2024-05-22 02:55 UTC, RadxaYuntian commented on arch/arm/mach-rockchip/misc.c
> +	if(!mac_read_from_eeprom())
bash写多了的恶果

2024-05-22 02:58 UTC, RadxaYuntian requested changes

2024-05-22 02:58 UTC, RadxaYuntian commented on drivers/misc/Kconfig
> +	 Set the MAC address through the obtained eeprom data.
```suggestion
         Enable support for Radxa ID EEPROM.
	 This EEPROM is used to store persistent platform data, such as MAC address.
```

2024-05-27 07:10 UTC, RadxaYuntian commented on drivers/misc/radxa-i2c-eeprom.c
你现在直接复制了一份代码，我们之后如果想要upstream这个修改的话很麻烦的，要一点点对比有什么区别

2024-05-27 08:14 UTC, Radxa-Alvin commented on drivers/misc/radxa-i2c-eeprom.c
当前我们用的数据定义已经跟 visionfive2 有很大的差异了，现阶段维护自己的就行了吧

2024-05-27 09:05 UTC, RadxaYuntian commented on drivers/misc/radxa-i2c-eeprom.c
https://applink.feishu.cn/client/message/link/open?token=AmWNV4OswsACZlRM2ooGgBw%3D

2024-05-27 09:05 UTC, RadxaYuntian approved these changes
https://applink.feishu.cn/client/message/link/open?token=AmWNV4OswsACZlRM2ooGgBw%3D

2024-05-27 09:05 UTC, merged