radxa-e25: blue light on when entering loader mode
radxa/u-boot pull request #87
Opened 2024-08-01 10:32 UTC by RadxaMitchell

Setting the state of the lamp via the gpio command When the recovery button is pressed to enter loader mode, the rgb led displays blue color.the blue light should be always on.

The number of the gpio pin that controls the rgb_blue lamp is 149 --> GPIO4_C5
The number of the gpio pin that controls the rgb_green lamp is 17 --> GPIO0_C1

2024-08-01 11:31 UTC, RadxaYuntian reviewed
U-Boot有LED命令，可以考虑和内核同步设备树后用LED命令来控制
另外#88 #89也应该是在同一个PR里面吧

2024-08-01 11:39 UTC, RadxaMitchell commented
#88 是和 #87 一起的，我分开提了
#89 是把波特率从 1500000 改为 115200 的

2024-08-05 08:44 UTC, RadxaYuntian approved these changes

2024-08-05 08:45 UTC, RadxaYuntian reviewed
没看到dts添加led的提交

2024-08-05 08:48 UTC, RadxaMitchell commented
dts 我在 #88 这个提在了这个 pr 里面，还没提交正在提

2024-08-05 08:49 UTC, RadxaYuntian commented
所以这两个就应该是在一个PR里面

2024-08-05 08:51 UTC, RadxaMitchell commented
那我把 #88 关掉，从新在这 pr 里面提交下

2024-08-05 09:03 UTC, RadxaYuntian requested changes

2024-08-05 09:03 UTC, RadxaYuntian commented on arch/arm/dts/rk3568-radxa-e25.dts
> +			default-state = "off";
```suggestion
```
只要我们用到`default-state`一般都是错误的用法：https://www.kernel.org/doc/Documentation/devicetree/bindings/leds/common.yaml

2024-08-05 10:08 UTC, RadxaYuntian approved these changes

2024-08-06 07:24 UTC, RadxaStephen commented
Added to branch next-dev-v2024.03.

2024-08-06 07:24 UTC, closed without merging