board: evb_rk3588: add startup by reading HW_ID
radxa/u-boot pull request #92
Opened 2024-08-29 08:20 UTC by RadxaMitchell

2024-08-29 08:27 UTC, RadxaYuntian requested changes

2024-08-29 08:27 UTC, RadxaYuntian commented on board/rockchip/evb_rk3588/evb_rk3588.c
> +	{"radxa,rock-5",   670, 710, "rockchip/rk3588s-rock-5a.dtb"},
这个定义了ITX就没法启动了

2024-08-29 08:27 UTC, RadxaYuntian commented on board/rockchip/evb_rk3588/evb_rk3588.c
> +	{"radxa,rock-5",   1670, 1710, "rockchip/rk3588s-radxa-e52c.dtb"},
前面这个compatible可能改成`rockchip,rk3588`可以减少其他设备树所需要的修改，后面L123会进行对比的，目前没有一个产品的compatible里面包含`radxa,rock-5`

2024-08-29 08:27 UTC, RadxaYuntian commented on include/configs/rk3588_common.h
> +#define CONFIG_ID_EEPROM
不能全部打开，只能在defconfig里面打开，不然ROCK5B就无法启动了

2024-08-30 04:12 UTC, RadxaMitchell commented
在原来的基础上又添加了 5T 和 E54C

2024-08-30 09:34 UTC, RadxaStephen commented
Added it to branch next-dev-v2024.03.

2024-08-30 09:34 UTC, closed without merging

2024-08-30 09:40 UTC, RadxaYuntian commented
defconfig都没有更新CONFIG_ID_EEPROM啊