rockchip: rk3588: Increase the MMU600PHP QOS to 4 for USB3_2
radxa/u-boot pull request #99
Opened 2024-09-24 09:46 UTC by Ken-Vamrs

This patch increases the MMU600PHP QOS from default 0 to 4 to get better transmission performance for USB3_2 & SATA0-2 & GMAC0-1.

Change-Id: I3a51483e41310c2abbca93a6a9c6e51d5ce50841

2024-09-24 09:47 UTC, Ken-Vamrs commented
RK redmine: https://redmine.rock-chips.com/issues/510020

2024-09-24 10:04 UTC, RadxaYuntian commented
少了0001-phy-rockchip-naneng-combophy-adjust-Rx-squelch-for-R.patch

2024-09-24 10:32 UTC, Ken-Vamrs commented
> 少了0001-phy-rockchip-naneng-combophy-adjust-Rx-squelch-for-R.patch

这个patch是kernel的，而且已经有合入的了

2024-09-25 02:00 UTC, RadxaYuntian approved these changes

2024-09-25 02:07 UTC, RadxaYuntian requested changes
看上去还有启动问题：https://redmine.rock-chips.com/issues/510020#change-5155839

2024-10-11 07:08 UTC, RadxaYuntian approved these changes

2024-10-11 07:37 UTC, merged